#title           :travis.yml
#description     :This script will communicate with travis CI
#author		       :Ajay Krishna Teja Kavuri
#date            :20160211
#version         :1.0
#==============================================================================

# Select the project language
language: python
#==============================================================================

# Select the project language
python:
  - "2.7"
#==============================================================================

# Cache
cache: pip
#==============================================================================

# Commands to run before the testing
before_script:
  # Install dependencies
  - pip install -r requirements.txt
#==============================================================================

# Run the actual test
script:
  # trigger unit testing for users data
  - python data/users/*Test.py
  - python data/src/*Test.py
  - python data/S3/*Test.py
